Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "vodka")
Ingredient.create(name: "tequila")
Ingredient.create(name: "rum")
Ingredient.create(name: "bitters")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "cranberry juice")
